apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: back
      app.kubernetes.io/name: test
      app.kubernetes.io/part-of: test
  template:
    metadata:
      labels:
        app.kubernetes.io/component: back
        app.kubernetes.io/name: test
        app.kubernetes.io/part-of: test
    spec:
      containers:
        - image: ghcr.io/andes-noh/example-app:d297b033
          name: app
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: "0.2"
              memory: 128M
